{% extends 'scag.toml' %}

{% block framework %}
application = "{{ application }}"
koajs_internal_unix_domain_socket = "{{ koajs_internal_unix_domain_socket }}"
{% endblock %}

{#- vim: set ft=jinja : #}
