{% extends 'scag.toml' %}

{% block framework %}
application = "{{ application }}"
expressjs_internal_unix_domain_socket = "{{ expressjs_internal_unix_domain_socket }}"
{% endblock %}

{#- vim: set ft=jinja : #}
