#!/usr/bin/expect -f

spawn scag-setup \
    --framework dotnet \
    --project_dir app \
    --target=hello_world \
    --bootstrap

lassign [wait] pid spawnid os_error_flag value

if {$os_error_flag == 0} {
    puts "exit status: $value"
} else {
    puts "errno: $value"
    exit 1
}

set image ""
spawn scag-build --project_dir app --print-only-image

set timeout 900
expect {
    -re {sha256:([0-9a-f]+)} {
	set image $expect_out(1,string)
    }
    eof { exit 1 }
}

spawn docker run -it --rm \
    --device /dev/sgx_enclave \
    --volume /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket \
    "$image"

expect {
    "hello, world" { exit 0 }
    eof { exit 1 }
}
