{% block application %}
[application]
framework = "{{ framework }}"
sgx = {{ sgx|lower }}
{% if sgx_key != '' %}
sgx_key = "{{ sgx_key }}"
{% endif %}
{% endblock %}

[ {{framework }}]
{% block framework %}
{% endblock %}
