{% block application -%}
[application]
framework = "{{ scag.builder.framework }}"
# Uncomment this if you'd like to use custom templates
#templates = 'templates/'
{%- endblock %}

[{{ scag.builder.framework }}]
{% block framework %}
{%- endblock %}

{#- vim: set ft=jinja : #}
